# This image works fine.

FROM golang:1.9.1-alpine AS build

COPY . $GOPATH/src/github.com/takecy/tz
WORKDIR $GOPATH/src/github.com/takecy/tz

RUN go build -o tz .\
 && mv tz /usr/local/bin/


FROM alpine:3.6

RUN apk --no-cache add tzdata

COPY --from=build /usr/local/bin/tz /usr/local/bin/

CMD ["tz"]